In [5]:
import pandas as pd
import numpy as numpy

df= pd.read_csv("KNN(iris_flower_dataset).csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
#KNN Algorithm
#independent variable
x=df.iloc[:,:-1]
#dependent variable
y=df.iloc[:,4].values

In [7]:
#split dataset in training and test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [12]:
#feature scalling

from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(x_train)
x_train= scaler.transform(x_train)
x_test= scaler.transform(x_test)

In [14]:
#KNN Model

from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)
y_pred= classifier.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 0  0  7]
 [ 0  0 10]
 [ 0  0 13]]
